### ISSUE TITLE
Allow to customize kUpdateWatchdogInterval

### ISSUE THREAD

**Issue by radex** [tapwork/WatchdogInspector#1]
2 seconds is a bit high to my liking — I would've preferred the status bar to update more frequently. (I'm more concerned about FPS drops rather than general FPS trends...)

**Comment by tapwork** [comment]
good idea.
feel free to make a Pull request.
But I could do it this weekend, too.

**Comment by radex** [comment]
I'd be happy too after the weekend!

**Comment by tapwork** [comment]
:+1:

**Comment by tapwork** [comment]
@radex see https://github.com/tapwork/WatchdogInspector/releases/tag/0.2.0

**Comment by radex** [comment]
Thank you! 👌
