### ISSUE TITLE
Port to tvOS

### ISSUE THREAD

**Issue by Michelasso** [tapwork/WatchdogInspector#11]
I don't know if you're interested, but I made it working on tvOS. At least I get a "status bar" (just a CGRect) showing on top of the screen. This is the code modified, file "**TWWatchdogInspector.m**"

```
#pragma mark - UI Updates

+ (void)setupStatusView
{
#if TARGET_OS_IOS
    CGRect statusBarFrame = [UIApplication sharedApplication].statusBarFrame;
#elif TARGET_OS_TV
    CGRect statusBarFrame = CGRectMake(0, 0, 1920, 20);
#endif
    CGSize size =  statusBarFrame.size;
    CGRect frame = CGRectMake(0, 0, size.width, size.height);
    UIWindow *window = [[UIWindow alloc] initWithFrame:frame];
    window.rootViewController = [[TWWatchdogInspectorViewController alloc] init];
    [window setHidden:NO];
#if TARGET_OS_IOS
    window.windowLevel = UIWindowLevelStatusBar + 50;
#elif TARGET_OS_TV
    window.windowLevel = UIWindowLevelNormal + 50;
#endif
    kInspectorWindow = window;
}
```

I tested it in (yet another) port to tvOS of this [git](https://github.com/andrea-prearo/SwiftExamples/tree/master/SmoothScrolling/Client) on my Apple TV 4K. It compiles just fine (well.. after messing up with the project configuration to manage to actually make it compiling and importing as a tvOS framework - not an Objective C guy, here) and runs beautifully:

![screen shot 2018-08-06 at 11 16 43](https://user-images.githubusercontent.com/2322927/43708340-85dd2d72-996a-11e8-8d31-cf2585359720.png)

Although I am not sure if the fps text is supposed to overlap the chart.

**Comment by tapwork** [comment]
great stuff!! thanks! the overlapping is correct so far. looks good. 
You can also add a Pull Request with your changes. That'll be great

**Comment by Michelasso** [comment]
Ok, I will. I never did a Pull Request before, so be patient if I mess up a bit. Also I have no clue about how to manage the cocoapod files. Hopefully it won't matter.

**Comment by tapwork** [comment]
@Michelasso no worries. just take your time. Just let me know if you need help. it's relative simple. just fork, make your changes and start the PR

**Comment by Michelasso** [comment]
Ahhh.. I had to fork it first. That's why the button wasn't enabled. 😄

**Comment by Michelasso** [comment]
@tapwork All right! I actually managed to port the whole git to tvOS (minimum target 10.2), SwiftExample included, updating the Pod configuration as well!! All seems to be running fine!

After a "Pod install" one should just be able to select the target with the tvOS platform and compile/run it. I created a pull request already (this last is my 3rd commit) and I have seen that the 2nd pull somehow it failed. It must be due to the fact that I had to change the bundle identifiers (also don't look at them. I have a free developer account, so I am always reusing the same identifiers).

**Comment by tapwork** [comment]
@Michelasso I will have a look tomorrow. I am currently on the way to home ;-)

**Comment by Michelasso** [comment]
@tapwork sure, when you have the time. Hopefully there isn't any hidden mess. One thing, though: I don't like much that the framework gets the same name in both iOS and tvOS. It's fine when using it with the pods, but when just adding the framework source code and compiling it gets very confusing.  It's easy to end up linking the one for wrong the other platform.

**Comment by tapwork** [comment]
done with https://github.com/tapwork/WatchdogInspector/pull/12
