### ISSUE TITLE
Getting `TWWatchdogInspectorStallingTimeout` after doing a start > stop > start

### ISSUE THREAD

**Issue by haidalinda** [tapwork/WatchdogInspector#2]
I'm toggling whether Watchdog is running via a button, i.e not programatically. When I tap that button 3 times -  start > stop > start - the library invariably crashes with the `TWWatchdogInspectorStallingTimeout`. Should that be expected? And, if so, hoping to understand better why that's the case.

Thanks!

**Comment by tapwork** [comment]
Sounds not right. I will have a look this weekend

**Comment by tapwork** [comment]
@hkellaway fixed with https://github.com/tapwork/WatchdogInspector/releases/tag/0.2.0

**Comment by haidalinda** [comment]
awesome, thanks for the quick turnaround on that.

**Comment by haidalinda** [comment]
tested it out, no longer an issue :+1:
