### ISSUE TITLE
Unable to find a specification for `WatchdogInspector`

### ISSUE THREAD

**Issue by kidsid49** [tapwork/WatchdogInspector#5]
Having issue while installing via Cocoapods.
this line in pod file throws an error.
``pod 'WatchdogInspector'`

**Comment by tapwork** [comment]
You probably set your platform not to iOS 8
like
`platform :ios, '7.0'`

but the pod spec requires 
`platform :ios, '8.0'`

I fixed it with Version 0.2.1 https://github.com/tapwork/WatchdogInspector/releases/tag/0.2.1

**Comment by kidsid49** [comment]
I am using these lines in my pod file.
and platform is iOS 8 only.

```

platform :ios, '8.0'
use_frameworks!
```

`pod "WatchdogInspector"`

**Comment by tapwork** [comment]
and does it work now?
maybe try a `pod update WatchdogInspector`

**Comment by kidsid49** [comment]
With little debugging I am getting this message.
For the moment, I am gonna add it manually inside my app.

```
$ pod repo update --verbose

Updating spec repo `ios-pod-specs`
  $ /usr/bin/git pull --ff-only
  ERROR: Repository not found.
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.


Updating spec repo `master`
  $ /usr/bin/git pull --ff-only

```

**Comment by tapwork** [comment]
Maybe it has something to do with the GitHub / CocoaPods issue / rate limit due to the heavy load caused by CocoaPods
https://github.com/CocoaPods/CocoaPods/issues/4989#issuecomment-193772935
does it work with ?

```
pod 'WatchdogInspector', git: 'git@github.com:tapwork/WatchdogInspector.git'
```
