### ISSUE TITLE
Add ability to disable throwing TWWatchdogInspectorStallingTimeout exception

### ISSUE THREAD

**Issue by caoer** [tapwork/WatchdogInspector#8]
Would be good if it can add ability to disable throwing TWWatchdogInspectorStallingTimeout exception. While debugging the app, this will always be thrown and crash the app.

**Comment by tapwork** [comment]
good point...
I could do it soon...
until then you'd use a higher value for `setStallingThreshhold`

**Comment by tapwork** [comment]
@caoer now fixed with  https://github.com/tapwork/WatchdogInspector/releases/tag/1.0.0

**Comment by caoer** [comment]
@tapwork wonderful! thank you sir. 👍
