### ISSUE TITLE
Private API usage - confirmation needed.

### ISSUE THREAD

**Issue by pikor** [tapwork/WatchdogInspector#9]
HI!

In readme you wrote:

> Make sure that you don't use WatchdogInspector in production.

I would like to keep Watchdoginspector for sometime for my development and staging build. Hence, 

```
#if ENV_DEVELOPMENT || ENV_STAGING
    TWWatchdogInspector.setEnableMainthreadStallingException(false)
    TWWatchdogInspector.start()
#endif
```

and so my question is: is it enough to protect myself from app rejection? Does Watchdoginspector use any private API? I'm asking because in release mode Watchdoginspector framework is bundled inside *.ipa.

Best,
Pikor

**Comment by tapwork** [comment]
@pikor WatchdogInspector doesn't use private API.
Your macro is fine. You should not expect any rejections.

**Comment by pikor** [comment]
Perfect! Thank you for the clarification!
